language: node_js
script: echo "No test to run yet"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: dev-launchers/project-example
  target_branch: master
  on:
    branch: release